version: "3"
   
services:
    frontend:
        image: kubedevops2245/my-task:latest
        container_name: frontend
        ports:
          - 3000:3000
        depends_on: 
          - backend  

    backend:
        image: kubedevops2245/my-backend:latest
        container_name: backend
        command: python manage.py runserver 0.0.0.0:8000
        ports:
            - "8000:8000"